# render.yaml
services:
  - type: web
    name: websocket-relay
    env: node
    plan: free
    region: frankfurt      # closest EU region
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      # If you want a fixed local port for testing, you can define:
      # - key: PEERJS_PORT
      #   value: "28175"
      # Otherwise, leave it blank and rely on Render’s $PORT.
