# render.yaml
services:
  - type: web
    name: peerjs-server
    env: node
    plan: free
    region: frankfurt   # nearest EU region
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PEERJS_PATH
        value: "/ClawDrop"
      # No PEERJS_PORT here; server.js will pick up Render's $PORT
