# render.yaml
services:
  - type: web
    name: webrtc-signaling-server
    env: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install
    startCommand: node enhanced-relay-server.js
    envVars:
      - key: SERVER_IP
        value: 'peerjs-server-sv20.onrender.com'
      - key: NODE_ENV
        value: 'production'

  - type: web
    name: turn-server
    env: node
    plan: starter # TURN servers need more resources
    region: frankfurt
    branch: main
    buildCommand: npm install
    startCommand: node turn-server.js
    envVars:
      - key: NODE_ENV
        value: 'production'
